### ISSUE TITLE
[BUG] transcript slash-command 

### ISSUE THREAD

**Issue by thecmdradama** [discord-tickets/bot#382] opened 2023-02-06 15:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to take a transcript of a ticket. First thing to note is that no options are available.
![Screenshot 2023-02-06 230601](https://user-images.githubusercontent.com/44428944/217007514-754d8deb-aefb-4429-a8bd-f1f8d3b61719.png)

If you try to manually enter the ticket name or number the command errors with the following
```
[ERROR] (COMMANDS) "transcript" command execution error: Error: Ticket support-7 does not exist
    at TranscriptSlashCommand.fillTemplate (/var/lib/pufferpanel/servers/abb7ee01/src/commands/slash/transcript.js:65:22)
    at async TranscriptSlashCommand.run (/var/lib/pufferpanel/servers/abb7ee01/src/commands/slash/transcript.js:140:7)
```
or
```
[ERROR] (COMMANDS) "transcript" command execution error: Error: Ticket 8 does not exist
    at TranscriptSlashCommand.fillTemplate (/var/lib/pufferpanel/servers/abb7ee01/src/commands/slash/transcript.js:65:22)
    at async TranscriptSlashCommand.run (/var/lib/pufferpanel/servers/abb7ee01/src/commands/slash/transcript.js:140:7)
```

### Expected Behavior

What I would expect to see is the bot returns a unique URI to the archived copy of the ticket.

### Steps To Reproduce

1. On the Discord server create any new ticket.
2. type some content in the ticket.
3. Close the ticket
4. run the /transcript command from a channel that the bot has access.
5. Note that no tickets are found in the search.
6. enter a ticket number 
7. error should present.

### Environment

```markdown
- OS: Ubuntu 22.04.1
- Node: 18.14.0 LTS
- NPM: 9.3.1
- Bot: v4.0.0-beta.3
```

**Comment by eartharoid** [comment] 2023-02-06 17:25
You didn't mention closing the ticket in the steps to reproduce so I think this is actually the intended behaviour.
You can only get the transcript of a ticket that has been closed.

**Comment by thecmdradama** [comment] 2023-02-06 22:26
I'll update the steps because I have tried that as well and still no tickets are found.

**Closed** 2023-02-09 17:40 UTC
Labels: bug
