### ISSUE TITLE
[BUG] SyntaxError: Unexpected token < in JSON

### ISSUE THREAD

**Issue by KangleJangle** [discord-tickets/bot#516] opened 2024-01-13 18:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to start the bot up throws a SyntaxError message, will not allow publishing commands due to this.

### Expected Behavior

Expected the server to start and work properly.

### Steps To Reproduce

1. Run docker-compose command.
2. Wait.
3. Error

### Environment

```markdown
- OS: Ubuntu 22.04 Container
- Node: Node v20.11
- NPM: 10.2.4
- Bot: 4.0.13
```

### Anything else?

![Screenshot 2024-01-13 121304](https://github.com/discord-tickets/bot/assets/83674060/77c44250-9fb2-44fc-91c4-cf85e6588f9e)

**Comment by eartharoid** [comment] 2024-01-21 02:29
Duplicate of #506

**Closed by eartharoid** 2024-01-21 02:29 UTC
Labels: bug, duplicate
