### ISSUE TITLE
[BUG] log open and close a ticket in console

### ISSUE THREAD

**Issue by skylide** [discord-tickets/bot#234] opened 2021-09-11 21:07 UTC
**Describe the bug**
open a ticket and close a ticket and they are error on the console pterodactyl but it's work problaly 

```
2021-09-11 23:04:59 [ERROR] SequelizeDatabaseError: SQLITE_ERROR: foreign key mismatch - "dsctickets_user_entities" referencing "dsctickets_role_entities"
    at Query.formatError (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
    at Query._handleQueryResponse (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
    at Statement.errBack (/home/container/node_modules/sqlite3/lib/sqlite3.js:14:21)
2021-09-11 23:04:59 [WARN] Failed to update message author entity in ticket archive
2021-09-11 23:04:59 [ERROR] SequelizeDatabaseError: SQLITE_ERROR: foreign key mismatch - "dsctickets_user_entities" referencing "dsctickets_role_entities"
    at Query.formatError (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
    at Query._handleQueryResponse (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
    at Statement.errBack (/home/container/node_modules/sqlite3/lib/sqlite3.js:14:21)
2021-09-11 23:05:19 [INFO] (COMMANDS) Executing "fermer" command (invoked by Skylide - Arnaud Dupont#3239)
2021-09-11 23:05:20 [WARN] Failed to update message author entity in ticket archive
2021-09-11 23:05:20 [ERROR] SequelizeDatabaseError: SQLITE_ERROR: foreign key mismatch - "dsctickets_user_entities" referencing "dsctickets_role_entities"
    at Query.formatError (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
    at Query._handleQueryResponse (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
    at Statement.errBack (/home/container/node_modules/sqlite3/lib/sqlite3.js:14:21)
2021-09-11 23:05:20 [WARN] Failed to update message author entity in ticket archive
2021-09-11 23:05:20 [ERROR] SequelizeDatabaseError: SQLITE_ERROR: foreign key mismatch - "dsctickets_user_entities" referencing "dsctickets_role_entities"
    at Query.formatError (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
    at Query._handleQueryResponse (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
    at Statement.errBack (/home/container/node_modules/sqlite3/lib/sqlite3.js:14:21)
2021-09-11 23:05:23 [WARN] Failed to update message author entity in ticket archive
2021-09-11 23:05:23 [ERROR] SequelizeDatabaseError: SQLITE_ERROR: foreign key mismatch - "dsctickets_user_entities" referencing "dsctickets_role_entities"
    at Query.formatError (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
    at Query._handleQueryResponse (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
    at Statement.errBack (/home/container/node_modules/sqlite3/lib/sqlite3.js:14:21)
2021-09-11 23:05:23 [INFO] Skylide - Arnaud Dupont#3239 closed a ticket (886356672300339230)
2021-09-11 23:05:24 [WARN] Failed to update message author entity in ticket archive
2021-09-11 23:05:24 [ERROR] SequelizeDatabaseError: SQLITE_ERROR: foreign key mismatch - "dsctickets_user_entities" referencing "dsctickets_role_entities"
    at Query.formatError (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:403:16)
    at Query._handleQueryResponse (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/container/node_modules/sequelize/lib/dialects/sqlite/query.js:238:27)
    at Statement.errBack (/home/container/node_modules/sqlite3/lib/sqlite3.js:14:21)
```

**Comment by eartharoid** [comment] 2021-09-11 21:28
Duplicate of #162.
This can be ignored as it shouldn't affect usage of current features.

**Comment by skylide** [comment] 2021-09-11 22:04
Okay nice thx

**Closed** 2022-04-23 21:31 UTC
Labels: bug, duplicate
